# Deployment for a Postgres db used by OpenProject
# https://hub.docker.com/_/postgres


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openproject-postgresql-pvc
  namespace: openproject
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: openproject
data:
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openproject-postgresql
  namespace: openproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openproject-postgresql
  template:
    metadata:
      labels:
        app: openproject-postgresql
    spec:
      containers:
      - name: postgres
        image: docker.io/library/postgres:16.4-bookworm
        args: ["-c", "config_file=/etc/postgresql/postgresql.conf"]
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - openproject
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - openproject
          initialDelaySeconds: 5
          periodSeconds: 60
          failureThreshold: 3
        env:
        - name: POSTGRES_DB
          value: openproject
        - name: POSTGRES_USER
          value: openproject
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openproject-postgres-secret
              key: postgresql-password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: postgres-config
          mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: openproject-postgresql-pvc
      - name: postgres-config
        configMap:
          name: postgres-config
---
# Create a service for the postgres db
apiVersion: v1
kind: Service
metadata:
  name: openproject-postgresql
  namespace: openproject
spec:
  selector:
    app: openproject-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
