# This file contains the secrets for the openproject deployment
# https://www.openproject.org/
# https://www.openproject.org/docs/installation-and-operations/installation/helm-chart/


apiVersion: v1
kind: Secret
metadata:
  name: openproject-postgres-secret
  namespace: openproject
type: Opaque
stringData:
  password: "USER_PASSWORD"
  postgresql-password: "POSTGRES_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: openproject-s3-secret
  namespace: openproject
type: Opaque
stringData:
  accessKeyId: <YOUR_ACCESS_KEY>
  secretAccessKey: <YOUR_SECRET_ACCESS_KEY>
---
apiVersion: v1
kind: Secret
metadata:
  name: openproject-oidc-secret
  namespace: openproject
type: Opaque
stringData:
  clientId: <YOUR_CLIENT_ID>
  clientSecret: <YOUR_CLIENT_SECRET>
