# This file contains the secrets for the openproject deployment
# https://www.openproject.org/
# https://www.openproject.org/docs/installation-and-operations/installation/helm-chart/


apiVersion: v1
kind: Secret
metadata:
  name: openproject-postgres-secret
  namespace: openproject
type: Opaque
stringData:
  password: <YOUR_POSTGRES_PASSWORD>
  postgres-password: gs735shvsral3sgsf
---
apiVersion: v1
kind: Secret
metadata:
  name: openproject-secret
  namespace: openproject
type: Opaque
stringData:


  postgres-password: gs735shvsral3sgsf
  host: oneproject.torulethemall.org

  admin-email: <YOUR_ADMIN_EMAIL>
  admin-password: <YOUR_ADMIN_PASSWORD>
  
  postgres-user-password: <YOUR_POSTGRES_PASSWORD>
  s3-access-key: <YOUR_MINIO_ACCESS_KEY>
  s3-secret-key: <YOUR_MINIO_SECRET_KEY>

  # Email configuration
  EMAIL_DELIVERY_METHOD: "smtp"
  SMTP_ADDRESS: "smtp.example.net"
  SMTP_PORT: "587"
  SMTP_DOMAIN: "example.net"
  SMTP_AUTHENTICATION: "plain"
  SMTP_USER_NAME: "user"
  SMTP_PASSWORD: "password"
  SMTP_ENABLE_STARTTLS_AUTO: "true"
