apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvpn-pvc
  namespace: vpn-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 8Gi
