# K3s Kubernetes Deployment for a Tekxit Server
# https://www.technicpack.net/modpack/tekxit-3-official-1122.1253751
# https://github.com/j-brn/minecraft-tekxit-docker


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekxit-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 16Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekxit
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekxit
  template:
    metadata:
      labels:
        app: tekxit
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: tekxit
        image: knaeckebrothero/tekxit:1.2
        command: ["sh"]
        args: ["/server/ServerLinux.sh"]  # Updated path to match your container
        ports:
        - containerPort: 25565
          protocol: TCP
        resources:
          requests:
            cpu: 1000m
            memory: 8Gi
          limits:
            cpu: 3000m
            memory: 12Gi
        env:
        - name: JAVA_XMS
          value: "8G"
        - name: JAVA_XMX
          value: "10G"
        volumeMounts:
        - name: tekxit-data
          mountPath: /data
      volumes:
      - name: tekxit-data
        persistentVolumeClaim:
          claimName: tekxit-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node1
---
apiVersion: v1
kind: Service
metadata:
  name: tekxit-loadbalancer
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: tekxit
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
