# Operator settings go here
operator:
  namespace: rook-ceph

# Cluster settings go here
cluster:
  # Set to true to create a CephCluster CR
  enabled: true
  name: rook-ceph
  namespace: rook-ceph

  # Custom CephCluster settings
  placement:
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: ceph-osd
                  operator: In
                  values:
                    - enabled
  cephClusterSpec:
    cephVersion:
      image: quay.io/ceph/ceph:v18.2.4
      allowUnsupported: false
    dataDirHostPath: /var/lib/rook
    mon:
      count: 3
      allowMultiplePerNode: false
    mgr:
      count: 2
      allowMultiplePerNode: false
    dashboard:
      enabled: true
      ssl: true
    storage:
      useAllNodes: false
      useAllDevices: false
      nodes:
        - name: "server-node-1"
          deviceFilter: 'sd[c-d]'
        - name: "server-node-2"
          deviceFilter: 'sd[c-e]'
