# MinIO Tenant values for Nextcloud deployment
# https://min.io/
# kubectl kustomize https://github.com/minio/operator/examples/kustomization/base/ > tenant-base.yaml

# Secret for the MinIO Tenant configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-storage-configuration
  namespace: nextcloud
data:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="minio123"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
---
# Secret for the MinIO Tenant user
apiVersion: v1
kind: Secret
metadata:
  name: minio-storage-user
  namespace: nextcloud
type: Opaque
stringData:
  CONSOLE_ACCESS_KEY: root
  CONSOLE_SECRET_KEY: root123
---
# MinIO Tenant configuration
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
  labels:
    app: minio
  name: minio-nextcloud-tenant
  namespace: nextcloud
spec:
  certConfig: {}
  configuration:
    name: minio-storage-configuration
  env: []
  externalCaCertSecret: []
  externalCertSecret: []
  externalClientCertSecrets: []
  features:
    bucketDNS: false
    domains: {}
  image: quay.io/minio/minio:RELEASE.2024-08-17T01-24-54Z
  imagePullPolicy: IfNotPresent
  imagePullSecret: {}
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - affinity:
      nodeAffinity: {}
      podAffinity: {}
      # Pod anti-affinity to ensure that MinIO Tenant pods are not scheduled on the same node
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                v1.min.io/tenant: minio-nextcloud-tenant
            topologyKey: "kubernetes.io/hostname"
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    name: pool-0
    nodeSelector: {}
    resources:
        requests:
          cpu: 250m
          memory: 3Gi
        limits:
          cpu: 2000m
          memory: 9Gi
    securityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    # Total number of servers in the MinIO Tenant
    servers: 3
    tolerations: []
    topologySpreadConstraints: []
    volumeClaimTemplate:
      # Persistent volume claim template for the MinIO Tenant
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        name: hdd-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 750Gi
        storageClassName: longhorn-hdd-minio
      status: {}
    # Number of volumes per server
    volumesPerServer: 3
  priorityClassName: ""
  requestAutoCert: true
  serviceAccountName: ""
  serviceMetadata:
    consoleServiceAnnotations: {}
    consoleServiceLabels: {}
    minioServiceAnnotations: {}
    minioServiceLabels: {}
  subPath: ""
  users:
  - name: minio-storage-user
