FROM quay.io/keycloak/keycloak:latest AS builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure SQLite as database vendor
ENV KC_DB=dev-file

WORKDIR /opt/keycloak
# Build with only the necessary build-time options
RUN /opt/keycloak/bin/kc.sh build \
    --db=dev-file \
    --features=authorization,token-exchange,admin-fine-grained-authz \
    --http-relative-path=/

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# These runtime environment variables will handle the proxy settings
ENV KC_DB=dev-file
ENV KC_PROXY=edge
ENV KC_HOSTNAME_STRICT=false
ENV KC_HOSTNAME_STRICT_HTTPS=true
ENV KC_PROXY_ADDRESS_FORWARDING=true
ENV KC_HTTP_ENABLED=true
ENV KC_HTTPS_PROTOCOLS="TLSv1.3,TLSv1.2"
ENV KC_PROXY_HEADERS=xforwarded
ENV KC_HTTP_PORT=8080
ENV KC_HOSTNAME_STRICT_BACKCHANNEL=true

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
