# Deployment for a garage storage node
# https://garagehq.deuxfleurs.fr/


apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config-node1
  namespace: garage
data:
  garage.toml: |
    replication_factor = 3
    consistency_mode = "consistent"

    metadata_dir = "/var/lib/garage/meta"
    data_dir = [
        { path = "/var/lib/garage/data/hdd1", capacity = "3T" },
        { path = "/var/lib/garage/data/hdd1", capacity = "3T" },
    ]
    metadata_fsync = false
    data_fsync = false
    disable_scrub = false
    metadata_auto_snapshot_interval = "8h"

    db_engine = "lmdb"

    block_size = "1MiB"
    block_ram_buffer_max = "256MiB"

    lmdb_map_size = "1TiB"

    compression_level = 10

    rpc_secret = "a23110c37286ebeecabd6ca4e5f2b6cb0d0344f5f09338fc4cb2bc34a1665682"
    rpc_bind_addr = "[::]:3901"
    rpc_bind_outgoing = false
    rpc_public_addr = "[fc00:1::1]:3901"
    # or set rpc_public_adr_subnet to filter down autodiscovery to a subnet:
    # rpc_public_addr_subnet = "2001:0db8:f00:b00:/64"


    allow_world_readable_secrets = false

    bootstrap_peers = [
        "563e1ac825ee3323aa441e72c26d1030d6d4414aeb3dd25287c531e7fc2bc95d@[fc00:1::1]:3901",
        "86f0f26ae4afbd59aaf9cfb059eefac844951efd5b8caeec0d53f4ed6c85f332@[fc00:1::2]:3901",
        "681456ab91350f92242e80a531a3ec9392cb7c974f72640112f90a600d7921a4@[fc00:B::1]:3901",
        "212fd62eeaca72c122b45a7f4fa0f55e012aa5e24ac384a72a3016413fa724ff@[fc00:F::1]:3901",
    ]


    [consul_discovery]
    api = "catalog"
    consul_http_addr = "http://127.0.0.1:8500"
    service_name = "garage-daemon"
    ca_cert = "/etc/consul/consul-ca.crt"
    client_cert = "/etc/consul/consul-client.crt"
    client_key = "/etc/consul/consul-key.crt"
    # for `agent` API mode, unset client_cert and client_key, and optionally enable `token`
    # token = "abcdef-01234-56789"
    tls_skip_verify = false
    tags = [ "dns-enabled" ]
    meta = { dns-acl = "allow trusted" }


    [kubernetes_discovery]
    namespace = "garage"
    service_name = "garage-daemon"
    skip_crd = false


    [s3_api]
    api_bind_addr = "[::]:3900"
    s3_region = "garage"
    root_domain = ".s3.garage"

    [s3_web]
    bind_addr = "[::]:3902"
    root_domain = ".web.garage"

    [admin]
    api_bind_addr = "0.0.0.0:3903"
    metrics_token = "BCAdFjoa9G0KJR0WXnHHm7fs1ZAbfpI8iIZ+Z/a2NgI="
    admin_token = "UkLeGWEvHnXBqnueR3ISEMWpOnm40jH2tM2HnnL/0F4="
    trace_sink = "http://localhost:4317"