# This is a sample deployment file for Gitea server which can be used as version control for syncing your Obsidian notes.
# https://obsidian.md/
# https://about.gitea.com/


# Volumeclaim for the gitea data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 16Gi
---
# Deployment for the Gitea application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.22
        ports:
        - containerPort: 3000
        - containerPort: 22
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 512Mi
        volumeMounts:
        - name: gitea-data
          mountPath: /data
        env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
      volumes:
      - name: gitea-data
        persistentVolumeClaim:
          claimName: gitea-pvc
---
# NodePort service for the Gitea application
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: default
spec:
  selector:
    app: gitea
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 30022
  type: NodePort
