# K3s Kubernetes Deployment for a Teamspeak Server
# https://www.teamspeak.com/
# https://hub.docker.com/_/teamspeak/


# PersistentVolumeClaim for the Teamspeak Server
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamspeak-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 1Gi
---
# Deployment for the Teamspeak Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamspeak
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamspeak
  template:
    metadata:
      labels:
        app: teamspeak
    spec:
      containers:
      - name: teamspeak
        image: docker.io/library/teamspeak:3.13
        ports:
        - containerPort: 9987
          protocol: UDP
        - containerPort: 10011
        - containerPort: 30033
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: TS3SERVER_LICENSE
          value: "accept"
        volumeMounts:
        - name: teamspeak-data
          mountPath: /var/ts3server
      volumes:
      - name: teamspeak-data
        persistentVolumeClaim:
          claimName: teamspeak-pvc
---
# LoadBalancer to expose the Teamspeak Server ports (important for UDP!!!)
apiVersion: v1
kind: Service
metadata:
  name: teamspeak-loadbalancer
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: teamspeak
  ports:
    - name: voice
      protocol: UDP
      port: 9987
      targetPort: 9987
    - name: serverquery
      protocol: TCP
      port: 10011
      targetPort: 10011
    - name: filetransfer
      protocol: TCP
      port: 30033
      targetPort: 30033
