# K3s Kubernetes Deployment for a Postgres db used by Nextcloud
# https://hub.docker.com/_/postgres


# StrorageClass for the postgres db used by Nextcloud
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-db-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  # Use fast storage for the db
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 32Gi
---
# Create a deployment for the postgres used by Nextcloud
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-db
  template:
    metadata:
      labels:
        app: nextcloud-db
    spec:
      containers:
      - name: postgres
        image: docker.io/library/postgres:latest
        env:
        - name: POSTGRES_DB
          value: nextcloud
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: db-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: nextcloud-db-pvc
---
# Create a service for the postgres db
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  selector:
    app: nextcloud-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
