# K3s Kubernetes secrets for the Nextcloud deployment
# https://nextcloud.com/


# Create a secret for the db password
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-secret
  namespace: nextcloud
type: Opaque
stringData:
  db-password: <DB_PASSWORD_GOES_HERE>
---