# K3s Kubernetes Deployment for the Nextcloud application
# https://nextcloud.com/
# https://hub.docker.com/_/nextcloud
# https://github.com/docker-library/docs/blob/master/nextcloud/README.md


# PersistentVolumeClaim for the Nextcloud application
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 16Gi
---
# Deployment for the Nextcloud application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: docker.io/library/nextcloud:28.0.9-apache
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 1Ti
          limits:
            cpu: 3500m
            memory: 8Gi
        #readinessProbe:
        #  httpGet:
        #    path: /status.php
        #    port: 80
        #  initialDelaySeconds: 30  # Wait 30 seconds before first check
        #  periodSeconds: 10        # Check every 10 seconds
        #  failureThreshold: 3      # Allow 3 failures before marking as not ready
        #  timeoutSeconds: 5        # Each probe has 5 seconds to complete
        #livenessProbe:
        #  httpGet:
        #    path: /status.php
        #    port: 80
        #  initialDelaySeconds: 60  # Wait 1 minute before first check
        #  periodSeconds: 60        # Check every minute
        #  failureThreshold: 3      # Allow 3 failures before restarting
        #  timeoutSeconds: 10       # Each probe has 10 seconds to complete
        env:
        # Nextcloud settings
        - name: NEXTCLOUD_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: admin-username
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: admin-password
        - name: NEXTCLOUD_INIT_HTACCESS
          value: "true"

        # Apache settings
        - name: APACHE_DISABLE_REWRITE_IP
          value: "1"
        - name: TRUSTED_PROXIES
          value: 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 103.21.244.0/22 103.22.200.0/22 103.31.4.0/22 104.16.0.0/13 104.24.0.0/14 108.162.192.0/18 131.0.72.0/22 141.101.64.0/18 162.158.0.0/15 172.64.0.0/13 173.245.48.0/20 188.114.96.0/20 190.93.240.0/20 197.234.240.0/22 198.41.128.0/17
        - name: OVERWRITEPROTOCOL
          value: https
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: trusted-domains

        # Database connection settings
        - name: POSTGRES_HOST
          value: nextcloud-postgresql
        - name: POSTGRES_DB
          value: nextcloud
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: postgres-password

        # Redis connection settings
        - name: REDIS_HOST
          value: nextcloud-redis
        - name: REDIS_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: redis-password
        
        # MinIO Tenant settings
        - name: OBJECTSTORE_S3_BUCKET
          value: "nextcloud"
        - name: OBJECTSTORE_S3_HOST
          value: "minio-nextcloud-tenant-hl-svc.nextcloud.svc.cluster.local"
        - name: OBJECTSTORE_S3_PORT
          value: "9000"
        - name: OBJECTSTORE_S3_KEY
          valueFrom:
            secretKeyRef:
              name: minio-storage-user
              key: CONSOLE_ACCESS_KEY
        - name: OBJECTSTORE_S3_SECRET
          valueFrom:
            secretKeyRef:
              name: minio-storage-user
              key: CONSOLE_SECRET_KEY
        - name: OBJECTSTORE_S3_SSL
          value: "false"
        - name: OBJECTSTORE_S3_USEPATH_STYLE
          value: "true"
        - name: OBJECTSTORE_S3_AUTOCREATE
          value: "true"

        volumeMounts:
        - name: nextcloud-app
          mountPath: /var/www/html
      volumes:
      - name: nextcloud-app
        persistentVolumeClaim:
          claimName: nextcloud-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
