# K3s Kubernetes secrets for the Nextcloud deployment
# https://nextcloud.com/


# Create secrets for the Nextcloud deployment
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
type: Opaque
stringData:
  db-password: <PASSWORD_GOES_HERE>
  admin-password: <PASSWORD_GOES_HERE>
  redis-password: PASSWORD_GOES_HERE>
  