# K3s Kubernetes Deployment for a Postgres db used by Nextcloud
# https://hub.docker.com/_/postgres


# Volumeclaim for the postgres db
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-postgresql-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  # Use fast storage for the db
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 16Gi
---
# Config map for the db
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: nextcloud
data:
  postgresql.conf: |
    listen_addresses = '*'
    max_connections = 300
---
# Create a deployment for the postgresql db used by Nextcloud
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-postgresql
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-postgresql
  template:
    metadata:
      labels:
        app: nextcloud-postgresql
    spec:
      containers:
      - name: postgres
        image: docker.io/library/postgres:16.4-bookworm
        args: ["-c", "config_file=/etc/postgresql/postgresql.conf"]
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - nextcloud
          initialDelaySeconds: 30
          periodSeconds: 60  # Check every minute
          failureThreshold: 3  # Allow 3 failures before restarting
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - nextcloud
          initialDelaySeconds: 5
          periodSeconds: 60  # Check every minute
          failureThreshold: 3  # Allow 3 failures before marking as not ready
        env:
        - name: POSTGRES_DB
          value: nextcloud
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: postgres-password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: postgres-config
          mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: nextcloud-postgresql-pvc
      - name: postgres-config
        configMap:
          name: postgres-config
---
# Create a service for the postgres db
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-postgresql
  namespace: nextcloud
spec:
  selector:
    app: nextcloud-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
