# K3s Kubernetes secrets for the Nextcloud deployment
# https://nextcloud.com/


# Create secrets for the Nextcloud deployment 
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
type: Opaque
stringData:
  postgres-password: <POSTGRES_PASSWORD>
  redis-password: <REDIS_PASSWORD>
  trusted-domains: nextcloud.local <YOUR_DOMAIN>
  admin-username: <ADMIN_USERNAME>
  admin-password: <ADMIN_PASSWORD>
