# K3s Kubernetes secrets for the Nextcloud deployment
# https://nextcloud.com/
# https://github.com/minio/operator/tree/master/examples/kustomization/


# Create secrets for the Nextcloud deployment 
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
type: Opaque
stringData:
  postgres-password: <POSTGRES_PASSWORD>
  redis-password: <REDIS_PASSWORD>
  trusted-domains: nextcloud.local <YOUR_DOMAIN>
  admin-username: <ADMIN_USERNAME>
  admin-password: <ADMIN_PASSWORD>
---
# Secret for the MinIO Tenant configuration
apiVersion: v1
kind: Secret
metadata:
  name: minio-storage-configuration
  namespace: nextcloud
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="<MINIO_ROOT_USER>"
    export MINIO_ROOT_PASSWORD="<MINIO_ROOT_PASSWORD>"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
---
# Secret for the MinIO Tenant user
apiVersion: v1
kind: Secret
metadata:
  name: minio-storage-user
  namespace: nextcloud
type: Opaque
stringData:
  CONSOLE_ACCESS_KEY: <USER_NAME>
  CONSOLE_SECRET_KEY: <USER_PASSWORD>
