# K3s Kubernetes Deployment for a Postgres db used by Nextcloud
# https://hub.docker.com/_/postgres


# StrorageClass for the postgres db used by Nextcloud
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-postgresql-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  # Use fast storage for the db
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 32Gi
---
# Create a deployment for the postgres used by Nextcloud
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-postgresql
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-postgresql
  template:
    metadata:
      labels:
        app: nextcloud-postgresql
    spec:
      containers:
      - name: postgres
        image: docker.io/library/postgres:16.4-bookworm
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - nextcloud
          initialDelaySeconds: 30
          periodSeconds: 60  # Check every minute
          failureThreshold: 3  # Allow 3 failures before restarting
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - nextcloud
          initialDelaySeconds: 5
          periodSeconds: 60  # Check every minute
          failureThreshold: 3  # Allow 3 failures before marking as not ready
        env:
        - name: POSTGRES_DB
          value: nextcloud
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: postgres-password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: nextcloud-postgresql-pvc
---
# Create a service for the postgres db
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-postgresql
  namespace: nextcloud
spec:
  selector:
    app: nextcloud-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
