allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    field.cattle.io/description: A ssd based storage class for minios cache.
  creationTimestamp: '2024-09-26T09:03:59Z'
  managedFields:
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:allowVolumeExpansion: {}
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/description: {}
        f:parameters:
          .: {}
          f:dataLocality: {}
          f:diskSelector: {}
          f:fsType: {}
          f:numberOfReplicas: {}
          f:staleReplicaTimeout: {}
        f:provisioner: {}
        f:reclaimPolicy: {}
        f:volumeBindingMode: {}
      manager: rancher
      operation: Update
      time: '2024-09-26T09:03:59Z'
  name: longhorn-ssd-minio
  resourceVersion: '7058988'
  uid: aaf46e3b-3124-4a1a-8270-04e77f2d7214
parameters:
  dataLocality: strict-local
  diskSelector: ssd
  fsType: xfs
  numberOfReplicas: '1'
  staleReplicaTimeout: '2880'
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
