allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    field.cattle.io/description: A storage class for the garage block data.
  creationTimestamp: '2024-09-24T08:35:39Z'
  managedFields:
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:allowVolumeExpansion: {}
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/description: {}
        f:parameters:
          .: {}
          f:dataLocality: {}
          f:diskSelector: {}
          f:numberOfReplicas: {}
        f:provisioner: {}
        f:reclaimPolicy: {}
        f:volumeBindingMode: {}
      manager: rancher
      operation: Update
      time: '2024-09-24T08:35:39Z'
  name: longhorn-garage
  resourceVersion: '5964013'
  uid: e15622df-990d-481f-804e-bfc7fe16c02d
parameters:
  dataLocality: strict-local
  diskSelector: garage
  numberOfReplicas: '1'
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
