allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: '2024-09-25T15:05:20Z'
  managedFields:
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:allowVolumeExpansion: {}
        f:parameters:
          .: {}
          f:dataLocality: {}
          f:diskSelector: {}
          f:numberOfReplicas: {}
          f:staleReplicaTimeout: {}
        f:provisioner: {}
        f:reclaimPolicy: {}
        f:volumeBindingMode: {}
      manager: rancher
      operation: Update
      time: '2024-09-25T15:05:20Z'
  name: longhorn-hdd-minio
  resourceVersion: '6660908'
  uid: d5de95e2-7baf-4bc9-8936-928cd9152a84
parameters:
  dataLocality: strict-local
  diskSelector: hdd
  numberOfReplicas: '1'
  staleReplicaTimeout: '2880'
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate