allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: '2024-09-24T08:17:10Z'
  managedFields:
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:allowVolumeExpansion: {}
        f:parameters:
          .: {}
          f:dataLocality: {}
          f:diskSelector: {}
          f:numberOfReplicas: {}
          f:staleReplicaTimeout: {}
        f:provisioner: {}
        f:reclaimPolicy: {}
        f:volumeBindingMode: {}
      manager: rancher
      operation: Update
      time: '2024-09-24T08:17:10Z'
  name: longhorn-m2
  resourceVersion: '5957227'
  uid: b35a91fe-406d-4f86-aef8-310f709574c5
parameters:
  dataLocality: best-effort
  diskSelector: m2
  numberOfReplicas: '1'
  staleReplicaTimeout: '2880'
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
