allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    field.cattle.io/description: Storage class for hdd drives.
  creationTimestamp: '2024-09-09T19:01:21Z'
  managedFields:
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:allowVolumeExpansion: {}
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/description: {}
        f:parameters:
          .: {}
          f:dataLocality: {}
          f:diskSelector: {}
          f:numberOfReplicas: {}
        f:provisioner: {}
        f:reclaimPolicy: {}
        f:volumeBindingMode: {}
      manager: rancher
      operation: Update
      time: '2024-09-09T19:01:21Z'
  name: longhorn-hdd
  resourceVersion: '84599'
  uid: b3e06d4c-04a8-40b6-9450-6f7c8f79ef68
parameters:
  dataLocality: disabled
  diskSelector: hdd
  numberOfReplicas: '2'
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
