# Storage config for deployment garage-node1
# https://garagehq.deuxfleurs.fr/


# Metadata volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-metadata-node1
  namespace: garage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-m2
  resources:
    requests:
      storage: 32Gi
---
# Data volumes
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data-node1-hdd1
  namespace: garage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-garage
  resources:
    requests:
      storage: 3500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data-node1-hdd2
  namespace: garage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-garage
  resources:
    requests:
      storage: 1750Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data-node1-hdd3
  namespace: garage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-garage
  resources:
    requests:
      storage: 875Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data-node1-hdd4
  namespace: garage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-garage
  resources:
    requests:
      storage: 875Gi
