# Configuration toml for a garage deployment
# https://garagehq.deuxfleurs.fr/
 

replication_factor = 3
consistency_mode = "consistent"

metadata_dir = "/var/lib/garage/meta"
data_dir = [
    { path = "/var/lib/garage/data/hdd1", capacity = "3500G" },
    { path = "/var/lib/garage/data/hdd2", capacity = "1750G" },
    { path = "/var/lib/garage/data/hdd3", capacity = "875G" },
    { path = "/var/lib/garage/data/hdd4", capacity = "875G" },
]
metadata_fsync = false
data_fsync = false
disable_scrub = false
metadata_auto_snapshot_interval = "8h"

db_engine = "lmdb"

block_size = "1MiB"
block_ram_buffer_max = "256MiB"

lmdb_map_size = "1TiB"

compression_level = 10

rpc_secret = "<RPC_SECRET>"
rpc_bind_addr = "[::]:3901"
rpc_bind_outgoing = false
rpc_public_addr = "[fc00:1::1]:3901"
# or set rpc_public_adr_subnet to filter down autodiscovery to a subnet:
# rpc_public_addr_subnet = "2001:0db8:f00:b00:/64"


allow_world_readable_secrets = false

bootstrap_peers = [
    "garage-node1.garage:3901",
    "garage-node2.garage:3901",
    "garage-node3.garage:3901"
]

#[consul_discovery]
#api = "catalog"
#consul_http_addr = "http://127.0.0.1:8500"
#service_name = "garage-daemon"
#ca_cert = "/etc/consul/consul-ca.crt"
#client_cert = "/etc/consul/consul-client.crt"
#client_key = "/etc/consul/consul-key.crt"
# for `agent` API mode, unset client_cert and client_key, and optionally enable `token`
# token = "abcdef-01234-56789"
#tls_skip_verify = false
#tags = [ "dns-enabled" ]
#meta = { dns-acl = "allow trusted" }


[kubernetes_discovery]
namespace = "garage"
service_name = "garage-daemon"
skip_crd = false


[s3_api]
api_bind_addr = "[::]:3900"
s3_region = "garage"

#[admin]
#api_bind_addr = "0.0.0.0:3903"
#metrics_token = "BCAdFjoa9G0KJR0WXnHHm7fs1ZAbfpI8iIZ+Z/a2NgI="
#admin_token = "UkLeGWEvHnXBqnueR3ISEMWpOnm40jH2tM2HnnL/0F4="
#trace_sink = "http://localhost:4317"
