# Use butane to generate the ignition file
# Windows command: butane --pretty --strict config.bu --output config.ign
# Configuration for the first node (to initialize the cluster)
variant: fcos
version: 1.5.0

# User configuration
passwd:
  users:
    # CoreOS user with sudo privileges and SSH key for remote access
    - name: core 
      ssh_authorized_keys:
        - <SSH_PUBLIC_KEY>

# System services configuration
systemd:
  units:
    # Disable cloud-init services
    - name: nm-cloud-setup.service
      mask: true
    - name: nm-cloud-setup.timer
      mask: true

    # Setup weekly reboot timer (reboots at 02:00 every Tuesday, GMT timezone)
    - name: weekly-restart.timer
      enabled: true
      contents: |
        [Unit]
        Description=Weekly Restart

        [Timer]
        OnCalendar=Tue *-*-* 02:00:00
        Persistent=true

        [Install]
        WantedBy=multi-user.target

    # Install and configure kubernetes
    - name: k3s-install.service
      enabled: true
      contents: |
        [Unit]
        Description=Install k3s
        After=network-online.target
        Wants=network-online.target

        [Service]
        Type=oneshot
        # Use this for the first server node to initialize the cluster
        Environment="INSTALL_K3S_EXEC=server --cluster-init --tls-san 192.168.1.101,192.168.1.102,192.168.1.103 --node-external-ip=192.168.1.101"
        ExecStart=/bin/sh -c 'curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="$INSTALL_K3S_EXEC" sh -s - --write-kubeconfig-mode 644'
        RemainAfterExit=true

        [Install]
        WantedBy=multi-user.target

    # Setup zincati update service
    - name: zincati.service
      enabled: true
      contents: |
        [Unit]
        Description=Zincati Update Service
        After=network-online.target
        Wants=network-online.target

        [Service]
        Type=simple
        ExecStart=/usr/libexec/zincati agent -v
        Restart=on-failure
        RestartSec=5s

        [Install]
        WantedBy=multi-user.target

# Storage configuration
storage:
  disks:
    # Configure the main hard drive for the operating system
    - device: /dev/disk/by-id/coreos-boot-disk
      wipe_table: false
      partitions:
      - number: 4 # This is the root partition where the OS is installed
        label: root
        size_mib: 32768 # At least 8192
        resize: true
      - size_mib: 0 # This is the var partition, which will take up the rest of the disk
        label: var
    
    # Configure additional hard drives for Longhorn to use as storage
    - device: /dev/disk/by-id/ssd2000
      wipe_table: true
      partitions:
      - size_mib: 0
        start_mib: 0
        label: "ssd.1.2000"
    - device: /dev/disk/by-id/ssd1000
      wipe_table: true
      partitions:
      - size_mib: 0
        start_mib: 0
        label: "ssd.2.1000"
    - device: /dev/sdc
      wipe_table: true
      partitions:
      - size_mib: 0
        start_mib: 0
        label: sdc-hdd-2000
    - device: /dev/sdd
      wipe_table: true
      partitions:
      - size_mib: 0
        start_mib: 0
        label: sdd-hdd-1000
    - device: /dev/sde
      wipe_table: true
      partitions:
      - size_mib: 0
        start_mib: 0
        label: sde-hdd-1000

  # Configure file systems and mount them on the previously configured hard drives
  filesystems:
    # Mount the root partition
    - path: /var
      device: /dev/disk/by-partlabel/var
      format: ext4
      wipe_filesystem: true
      with_mount_unit: true
  
    # Mount the additional hard drives
    - path: /var/lib/longhorn/sda-ssd-2000
      device: /dev/disk/by-partlabel/sda-ssd-2000
      format: ext4
      wipe_filesystem: true
      with_mount_unit: true
    - path: /var/lib/longhorn/sdb-ssd-1000
      device: /dev/disk/by-partlabel/sdb-ssd-1000
      format: ext4
      wipe_filesystem: true
      with_mount_unit: true
    - path: /var/lib/longhorn/sdc-hdd-4000
      device: /dev/disk/by-partlabel/sdc-hdd-4000
      format: ext4
      wipe_filesystem: true
      with_mount_unit: true
    - path: /var/lib/longhorn/sdd-hdd-4000
      device: /dev/disk/by-partlabel/sdd-hdd-4000
      format: ext4
      wipe_filesystem: true
      with_mount_unit: true
  
  # Create directories
  directories:
    - path: /var/lib/longhorn
      mode: 0644

  # Create files
  files:
    # Set the hostname
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: server-node-1
    
    # Confiure a longer shutdown timeout
    - path: /etc/systemd/system.conf.d/90-custom.conf
      mode: 0644
      contents:
        inline: |
          [Manager]
          DefaultTimeoutStopSec=300s
          DefaultTimeoutStartSec=90s

    # Config file for zincati
    - path: /etc/zincati/config.d/90-custom.toml
      overwrite: true
      mode: 0644
      contents:
        inline: |
          [updates]
          strategy = "periodic"
          periodic.interval_minutes = 10080 # Checks for updates every 7 days

          [updates.allow_downgrade]
          enabled = false  # Avoid downgrades

          [reboot]
          strategy = "off" # Disable reboot, since server reboots on daily basis anyway
