# Use butane to generate the ignition file
# Windows command: butane --pretty --strict config.bu --output config.ign
# Configuration for the third server node
variant: fcos
version: 1.5.0

# User configuration
passwd:
  users:
    # CoreOS user with sudo privileges and SSH key for remote access
    - name: core 
      ssh_authorized_keys:
        - ssh-ed25519 <SSH KEY>

# System services configuration
systemd:
  units:
    # Disable cloud-init services
    - name: nm-cloud-setup.service
      mask: true
    - name: nm-cloud-setup.timer
      mask: true

    # Setup daily reboot timer (reboots every day, gmt timezone)
    - name: daily-restart.timer
      enabled: true
      contents: |
        [Unit]
        Description=Daily Restart

        [Timer]
        OnCalendar=*-*-* 02:45:00
        Persistent=true

        [Install]
        WantedBy=multi-user.target

    # Setup a service that get's triggered by the timer to reboot the system
    - name: daily-restart.service
      enabled: true
      contents: |
        [Unit]
        Description=Trigger Daily Restart

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/systemctl reboot

        [Install]
        WantedBy=timer.target

    # Install and configure kubernetes
    - name: k3s-install.service
      enabled: true
      contents: |
        [Unit]
        Description=Install k3s
        After=network-online.target
        Wants=network-online.target

        [Service]
        Type=oneshot
        # Use this for the third node to join the cluster     
        Environment="INSTALL_K3S_EXEC=server --server https://192.168.1.101:6443 --tls-san 192.168.1.101,192.168.1.102,192.168.1.103 --node-external-ip=192.168.1.103"
        Environment="K3S_TOKEN=<TOKEN>"
        ExecStart=/bin/sh -c 'curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="$INSTALL_K3S_EXEC" K3S_TOKEN="$K3S_TOKEN" sh -s - --write-kubeconfig-mode 644'
        RemainAfterExit=true

        [Install]
        WantedBy=multi-user.target

    # Setup zincati update service
    - name: zincati.service
      enabled: true
      contents: |
        [Unit]
        Description=Zincati Update Service
        After=network-online.target
        Wants=network-online.target

        [Service]
        Type=simple
        ExecStart=/usr/libexec/zincati agent -v
        Restart=on-failure
        RestartSec=5s

        [Install]
        WantedBy=multi-user.target

# Storage configuration
storage:
  disks:
    # Configure the main hard drive for the operating system
    - device: /dev/disk/by-id/coreos-boot-disk
      wipe_table: false
      partitions:
      - number: 4 # This is the root partition where the OS is installed
        label: root
        size_mib: 16384 # At least 8192
        resize: true
      - size_mib: 0 # This is the var partition, which will take up the rest of the disk
        label: var

    # Configure the additional storage
    - device: /dev/disk/by-id/wwn-<WWN>
      wipe_table: true
      partitions:
      - number: 1
        label: ssd-2tb-1
        size_mib: 0
        start_mib: 0
    
    # Configure the harddrives for garage object storage
    # Since these are bigger than 2tb, they need to be formatted manually before the installation
    - device: /dev/disk/by-id/wwn-<WWN>
      wipe_table: false
      partitions:
      - number: 1
        label: hdd-4tb-1
    - device: /dev/disk/by-id/wwn-<WWN>
      wipe_table: false
      partitions:
      - number: 1
        label: hdd-4tb-2

  # Configure file systems and mount them on the previously configured hard drives
  filesystems:
    # Mount the root partition
    - path: /var
      device: /dev/disk/by-partlabel/var
      format: xfs
      wipe_filesystem: true
      with_mount_unit: true

    # Mount the additional hard drives
    - path: /var/lib/longhorn/ssd1
      device: /dev/disk/by-partlabel/ssd-2tb-1
      format: xfs
      wipe_filesystem: true
      with_mount_unit: true

    # Mount the harddrives for garage object storage
    # Again we do not whipe them since they have been formatted pre installation
    - path: /var/lib/longhorn/hdd1
      device: /dev/disk/by-partlabel/hdd-4tb-1
      format: xfs
      with_mount_unit: true
    - path: /var/lib/longhorn/hdd2
      device: /dev/disk/by-partlabel/hdd-4tb-2
      format: xfs
      with_mount_unit: true

  # Create directories
  directories:
    - path: /var/lib/longhorn
      mode: 0644

  # Create files
  files:
    # Set the hostname
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: node3

    # Confiure a longer shutdown timeout
    - path: /etc/systemd/system.conf.d/90-custom.conf
      mode: 0644
      contents:
        inline: |
          [Manager]
          DefaultTimeoutStopSec=600s
          DefaultTimeoutStartSec=300s

    # Config file for zincati
    - path: /etc/zincati/config.d/90-custom.toml
      overwrite: true
      mode: 0644
      contents:
        inline: |
          [updates]
          strategy = "periodic"
          periodic.interval_minutes = 10080 # Checks for updates every 7 days

          [updates.allow_downgrade]
          enabled = false  # Avoid downgrades

          [reboot]
          strategy = "off" # Disable reboot, since server reboots on daily basis anyway
