# A configuration file to override the default values of the MinIO Helm chart
# helm install minio minio/minio -f minio-value-override.yaml -n minio
# https://min.io/


mode: distributed
replicas: 2

# Server deployment configuration
persistence:
  enabled: true
  storageClass: "longhorn-ssd"
  size: 16Gi

# Data volume configuration
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "longhorn-minio-hdd"
  resources:
    requests:
      storage: 512Gi

# Define the drives MinIO will use
drives:
  - /export/data{1...4}

resources:
  requests:
    cpu: 250m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 4Gi
rootUser: "<USERNAME>"
rootPassword: "<PASSWORD>"
service:
  type: ClusterIP # Makes it available at: minio.minio.svc.cluster.local (port 9000)
ingress:
  enabled: false  # Disabled the ingress since we only want to access it from within the cluster
service:
  type: ClusterIP
consoleIngress:
  enabled: true
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/issuer: "minio"
    cert-manager.io/issuer-kind: Issuer
  hosts:
    - minio.local
  tls:
    - secretName: minio-console-local-tls
      hosts:
        - minio.local
