# A configuration file to override the default values of the MinIO Helm chart
# helm install minio minio/minio -f minio-value-override.yaml -n minio
# https://min.io/


operator:
  additionalLabels: {}
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: name
                operator: In
                values:
                  - minio-operator
          topologyKey: kubernetes.io/hostname
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  env:
    - name: OPERATOR_STS_ENABLED
      value: 'on'
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/minio/operator
    tag: v6.0.3
  imagePullSecrets: []
  initContainers: []
  nodeSelector: {}
  priorityClassName: ''
  replicaCount: 1
  resources:
    requests:
      cpu: 200m
      ephemeral-storage: 500Mi
      memory: 256Mi
  runtimeClassName: null
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountAnnotations: []
  sidecarImage: {}
  tolerations: []
  topologySpreadConstraints: []
  volumeMounts: []
  volumes: []
global:
  cattle:
    systemProjectId: p-5d6pn
