# MinIO Tenant configuration
# https://min.io/
# https://github.com/minio/operator/tree/master/examples/kustomization/


# Secret for the minio tenant configuration (including the root credentials)
apiVersion: v1
kind: Secret
metadata:
  name: minio-storage-configuration
  namespace: minio-tenant
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="<MINIO_ROOT_USER>"
    export MINIO_ROOT_PASSWORD="<MINIO_ROOT_PASSWORD>"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
---
# Secret for the tenants admin user
apiVersion: v1
kind: Secret
metadata:
  name: minio-storage-user
  namespace: minio-tenant
type: Opaque
stringData:
  CONSOLE_ACCESS_KEY: <USER_NAME>
  CONSOLE_SECRET_KEY: <USER_PASSWORD>