annotations: {}
csi:
  attacherReplicaCount: null
  kubeletRootDir: null
  provisionerReplicaCount: null
  resizerReplicaCount: null
  snapshotterReplicaCount: null
defaultSettings:
  allowCollectingLonghornUsageMetrics: true
  allowEmptyDiskSelectorVolume: null
  allowEmptyNodeSelectorVolume: null
  allowRecurringJobWhileVolumeDetached: null
  allowVolumeCreationWithDegradedAvailability: null
  autoCleanupRecurringJobBackupSnapshot: null
  autoCleanupSnapshotWhenDeleteBackup: null
  autoCleanupSystemGeneratedSnapshot: null
  autoDeletePodWhenVolumeDetachedUnexpectedly: null
  autoSalvage: null
  backingImageCleanupWaitInterval: null
  backingImageRecoveryWaitInterval: null
  backupCompressionMethod: null
  backupConcurrentLimit: null
  backupTarget: null
  backupTargetCredentialSecret: null
  backupstorePollInterval: null
  concurrentAutomaticEngineUpgradePerNodeLimit: null
  concurrentReplicaRebuildPerNodeLimit: null
  concurrentVolumeBackupRestorePerNodeLimit: null
  createDefaultDiskLabeledNodes: null
  defaultDataLocality: null
  defaultDataPath: null
  defaultLonghornStaticStorageClass: null
  defaultReplicaCount: 2
  deletingConfirmationFlag: true
  detachManuallyAttachedVolumesWhenCordoned: null
  disableRevisionCounter: 'true'
  disableSchedulingOnCordonedNode: null
  disableSnapshotPurge: null
  engineReplicaTimeout: null
  failedBackupTTL: null
  fastReplicaRebuildEnabled: true
  freezeFilesystemForSnapshot: null
  guaranteedInstanceManagerCPU: null
  kubernetesClusterAutoscalerEnabled: null
  logLevel: null
  longGRPCTimeOut: null
  nodeDownPodDeletionPolicy: null
  nodeDrainPolicy: null
  orphanAutoDeletion: true
  priorityClass: longhorn-critical
  recurringFailedJobsHistoryLimit: null
  recurringJobMaxRetention: null
  recurringSuccessfulJobsHistoryLimit: null
  removeSnapshotsDuringFilesystemTrim: true
  replicaAutoBalance: null
  replicaDiskSoftAntiAffinity: null
  replicaFileSyncHttpClientTimeout: null
  replicaReplenishmentWaitInterval: null
  replicaSoftAntiAffinity: null
  replicaZoneSoftAntiAffinity: null
  restoreConcurrentLimit: null
  restoreVolumeRecurringJobs: null
  rwxVolumeFastFailover: null
  snapshotDataIntegrity: enabled
  snapshotDataIntegrityCronjob: 0 2 * * *
  snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: null
  snapshotMaxCount: null
  storageMinimalAvailablePercentage: null
  storageNetwork: null
  storageOverProvisioningPercentage: null
  storageReservedPercentageForDefaultDisk: null
  supportBundleFailedHistoryLimit: null
  systemManagedComponentsNodeSelector: null
  systemManagedPodsImagePullPolicy: null
  taintToleration: null
  upgradeChecker: null
  v1DataEngine: true
  v2DataEngine: null
  v2DataEngineGuaranteedInstanceManagerCPU: null
  v2DataEngineHugepageLimit: null
  v2DataEngineLogFlags: null
  v2DataEngineLogLevel: null
enableGoCoverDir: false
enablePSP: false
global:
  cattle:
    windowsCluster:
      defaultSetting:
        systemManagedComponentsNodeSelector: kubernetes.io/os:linux
        taintToleration: cattle.io/os=linux:NoSchedule
      enabled: false
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          key: cattle.io/os
          operator: Equal
          value: linux
    systemProjectId: p-5d6pn
  nodeSelector: {}
  tolerations: []
image:
  csi:
    attacher:
      repository: rancher/mirrored-longhornio-csi-attacher
      tag: v4.6.1
    livenessProbe:
      repository: rancher/mirrored-longhornio-livenessprobe
      tag: v2.14.0
    nodeDriverRegistrar:
      repository: rancher/mirrored-longhornio-csi-node-driver-registrar
      tag: v2.12.0
    provisioner:
      repository: rancher/mirrored-longhornio-csi-provisioner
      tag: v4.0.1
    resizer:
      repository: rancher/mirrored-longhornio-csi-resizer
      tag: v1.11.1
    snapshotter:
      repository: rancher/mirrored-longhornio-csi-snapshotter
      tag: v7.0.2
  longhorn:
    backingImageManager:
      repository: rancher/mirrored-longhornio-backing-image-manager
      tag: v1.7.1
    engine:
      repository: rancher/mirrored-longhornio-longhorn-engine
      tag: v1.7.1
    instanceManager:
      repository: rancher/mirrored-longhornio-longhorn-instance-manager
      tag: v1.7.1
    manager:
      repository: rancher/mirrored-longhornio-longhorn-manager
      tag: v1.7.1
    shareManager:
      repository: rancher/mirrored-longhornio-longhorn-share-manager
      tag: v1.7.1
    supportBundleKit:
      repository: rancher/mirrored-longhornio-support-bundle-kit
      tag: v0.0.42
    ui:
      repository: rancher/mirrored-longhornio-longhorn-ui
      tag: v1.7.1
  openshift:
    oauthProxy:
      repository: rancher/mirrored-longhornio-openshift-origin-oauth-proxy
      tag: 4.15
  pullPolicy: IfNotPresent
  defaultImage: true
ingress:
  annotations: null
  enabled: false
  host: sslip.io
  ingressClassName: null
  path: /
  pathType: ImplementationSpecific
  secrets: null
  secureBackends: false
  tls: false
  tlsSecret: longhorn.local-tls
longhornDriver:
  nodeSelector: {}
  priorityClass: longhorn-critical
  tolerations: []
longhornManager:
  log:
    format: plain
  nodeSelector: {}
  priorityClass: longhorn-critical
  serviceAnnotations: {}
  tolerations: []
longhornUI:
  nodeSelector: {}
  priorityClass: longhorn-critical
  replicas: 2
  tolerations: []
metrics:
  serviceMonitor:
    additionalLabels: {}
    annotations: {}
    enabled: false
    interval: ''
    metricRelabelings: []
    relabelings: []
    scrapeTimeout: ''
namespaceOverride: ''
networkPolicies:
  enabled: false
  type: k3s
openshift:
  enabled: false
  ui:
    port: 443
    proxy: 8443
    route: longhorn-ui
persistence:
  backingImage:
    dataSourceParameters: null
    dataSourceType: null
    enable: false
    expectedChecksum: null
    name: null
  defaultClass: true
  defaultClassReplicaCount: 2
  defaultDataLocality: best-effort
  defaultDiskSelector:
    enable: true
    selector: ssd
  defaultFsType: xfs
  defaultMkfsParams: ''
  defaultNodeSelector:
    enable: false
    selector: ''
  disableRevisionCounter: 'true'
  migratable: false
  nfsOptions: ''
  reclaimPolicy: Delete
  recurringJobSelector:
    enable: false
    jobList: []
  removeSnapshotsDuringFilesystemTrim: ignored
preUpgradeChecker:
  jobEnabled: true
  upgradeVersionCheck: true
privateRegistry:
  createSecret: null
  registryPasswd: null
  registrySecret: null
  registryUrl: null
  registryUser: null
service:
  manager:
    nodePort: ''
    type: ClusterIP
  ui:
    nodePort: null
    type: ClusterIP
serviceAccount:
  annotations: {}
longhorn:
  default_setting: false
