# Stores the longhorn backup target credentials
# https://longhorn.io/docs/1.6.2/snapshots-and-backups/backup-and-restore/set-backup-target/

apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-target
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: <YOUR_MINIO_ACCESS_KEY>
  AWS_SECRET_ACCESS_KEY: <YOUR_MINIO_SECRET_KEY>
  AWS_ENDPOINTS: http://minio-tenant-hl.minio-tenant.svc.cluster.local:9000
