apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.12"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongodb-admin-password
      roles:
        - name: mongoadmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: mongodb-admin-scram
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: longhorn-ssd
            resources:
              requests:
                storage: 64Gi
      template:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app: mongodb-community
                  topologyKey: "kubernetes.io/hostname"
          containers:
            - name: mongodb-agent
              readinessProbe:
                failureThreshold: 50
                periodSeconds: 15
              resources:
                requests:
                  cpu: "100m"
                  memory: "500Mi"
                limits:
                  cpu: "1"
                  memory: "2Gi"
            - name: mongod
              resources:
                requests:
                  cpu: "500m"
                  memory: "2Gi"
                limits:
                  cpu: "3"
                  memory: "8Gi"
  additionalMongodConfig:
    storage:
      wiredTiger:
        engineConfig:
          cacheSizeGB: 1
    operationProfiling:
      mode: slowOp
      slowOpThresholdMs: 100
